### ISSUE TITLE
No module named 'modules.inpainters.lama.saicinpainting.training.data'

### ISSUE THREAD

**Issue by arvrschool** [perf-project/PeRF#1]
Thanks for your work. I found one problem as the title when I run your released code, I think you forgot to upload this code.
Looking forward to your reply.

**Comment by Totoro97** [comment]
Hi, thanks for reporting this issue. The missing files are correspondingly uploaded.

**Comment by Wanggcong** [comment]
Since there are no further questions, I closed the issue. You might re-open it if necessary.
